#!/usr/bin/env bash
# Creates 6 milestones (Month 1-6) and one issue per week.
# Prerequisite: `gh auth login` already done; run from the repo root.
set -euo pipefail

gh api repos/:owner/:repo/milestones -f title="Month 1" -f description="Python package \`spacecraft-dynamics-core\` – attitude representations, rigid-body propagator, orbit propagator, fully unit-tested and documented."
gh api repos/:owner/:repo/milestones -f title="Month 2" -f description="Testbed stage 1 is running: the microcontroller reads the IMU in real time, drives the BLDC reaction wheel via PWM, and switches between operating modes – all observable over a serial logger and documented in the repo (\`firmware/\`) with an architecture diagram."
gh api repos/:owner/:repo/milestones -f title="Month 3" -f description="A real-time MEKF runs on the hardware and estimates orientation from real sensor data – compared against the software simulation and an independent reference measurement."
gh api repos/:owner/:repo/milestones -f title="Month 4" -f description="A physical single-axis demonstrator that detumbles itself and holds/tracks a target orientation – using exclusively a self-built reaction-wheel actuator, your own firmware (state machine, FDIR, control, FOC), and your own MEKF."
gh api repos/:owner/:repo/milestones -f title="Month 5" -f description="Python package \`flight-dynamics-toolkit\` – orbit determination, maneuver planning/delta-v budget, RPO trajectory planning including Monte Carlo validation, cross-validated against Orekit/GMAT."
gh api repos/:owner/:repo/milestones -f title="Month 6" -f description="A fully integrated, publicly documented \`cubesat-gnc-testbed\` repository with an SIL+HIL demonstration, a technical report, and a directly usable job-application portfolio."

gh issue create --title "Week 00 – Project Setup" --body "See docs/weeks/week00.md" --milestone "Month 1"
gh issue create --title "Week 01 – Mathematical Foundations & Attitude Representations" --body "See docs/weeks/week01.md" --milestone "Month 1"
gh issue create --title "Week 02 – Attitude Kinematics & Dynamics" --body "See docs/weeks/week02.md" --milestone "Month 1"
gh issue create --title "Week 03 – Orbital Mechanics I (Keplerian Orbits)" --body "See docs/weeks/week03.md" --milestone "Month 1"
gh issue create --title "Week 04 – Orbital Mechanics II (Perturbations, J2)" --body "See docs/weeks/week04.md" --milestone "Month 1"
gh issue create --title "Week 05 – System Architecture & Sensor/Actuator Selection" --body "See docs/weeks/week05.md" --milestone "Month 2"
gh issue create --title "Week 06 – Hardware Bring-up" --body "See docs/weeks/week06.md" --milestone "Month 2"
gh issue create --title "Week 07 – I/O, Timers, Interrupts" --body "See docs/weeks/week07.md" --milestone "Month 2"
gh issue create --title "Week 08 – State Machines & Watchdog" --body "See docs/weeks/week08.md" --milestone "Month 2"
gh issue create --title "Week 09 – Static Attitude Determination" --body "See docs/weeks/week09.md" --milestone "Month 3"
gh issue create --title "Week 10 – Kalman Filter Fundamentals" --body "See docs/weeks/week10.md" --milestone "Month 3"
gh issue create --title "Week 11 – Multiplicative EKF for Attitude Estimation" --body "See docs/weeks/week11.md" --milestone "Month 3"
gh issue create --title "Week 12 – MEKF on Hardware" --body "See docs/weeks/week12.md" --milestone "Month 3"
gh issue create --title "Week 13 – Quaternion Feedback Control" --body "See docs/weeks/week13.md" --milestone "Month 4"
gh issue create --title "Week 14 – Detumbling, Momentum Dumping, Motor PID" --body "See docs/weeks/week14.md" --milestone "Month 4"
gh issue create --title "Week 15 – Field-Oriented Control (FOC)" --body "See docs/weeks/week15.md" --milestone "Month 4"
gh issue create --title "Week 16 – Closed Control Loop on Hardware" --body "See docs/weeks/week16.md" --milestone "Month 4"
gh issue create --title "Week 17 – Test Campaign & Characterization (Buffer)" --body "See docs/weeks/week17.md" --milestone "Month 4"
gh issue create --title "Week 18 – Orbit Determination" --body "See docs/weeks/week18.md" --milestone "Month 5"
gh issue create --title "Week 19 – Maneuver Planning & Delta-V Budget" --body "See docs/weeks/week19.md" --milestone "Month 5"
gh issue create --title "Week 20 – Rendezvous & Proximity Operations" --body "See docs/weeks/week20.md" --milestone "Month 5"
gh issue create --title "Week 21 – Monte Carlo Validation" --body "See docs/weeks/week21.md" --milestone "Month 5"
gh issue create --title "Week 22 – Autonomous Orbit Control (Buffer)" --body "See docs/weeks/week22.md" --milestone "Month 5"
gh issue create --title "Week 23 – Software-in-the-Loop (SIL)" --body "See docs/weeks/week23.md" --milestone "Month 6"
gh issue create --title "Week 24 – Hardware-in-the-Loop (HIL)" --body "See docs/weeks/week24.md" --milestone "Month 6"
gh issue create --title "Week 25 – ECSS-Style Documentation" --body "See docs/weeks/week25.md" --milestone "Month 6"
gh issue create --title "Week 26 – Portfolio & Job Application (overall milestone)" --body "See docs/weeks/week26.md" --milestone "Month 6"
