#!/usr/bin/env bash
# Legt 6 Milestones (Monat 1-6) und pro Woche ein Issue an.
# Voraussetzung: `gh auth login` bereits ausgeführt, im Repo-Root laufen lassen.
set -euo pipefail

gh api repos/:owner/:repo/milestones -f title="Monat 1" -f description="Python-Paket \`spacecraft-dynamics-core\` – Lage-Repräsentationen, Starrkörper-Propagator, Orbit-Propagator, vollständig unit-getestet und dokumentiert."
gh api repos/:owner/:repo/milestones -f title="Monat 2" -f description="Testbed-Stufe 1 läuft: Mikrocontroller liest IMU in Echtzeit, steuert BLDC-Reaktionsrad per PWM, schaltet zwischen Betriebsmodi – alles über seriellen Logger einsehbar und im Repo (\`firmware/\`) mit Architekturdiagramm dokumentiert."
gh api repos/:owner/:repo/milestones -f title="Monat 3" -f description="Echtzeit-MEKF läuft auf der Hardware und schätzt die Orientierung aus echten Sensordaten – verglichen mit Software-Simulation und einer unabhängigen Referenzmessung."
gh api repos/:owner/:repo/milestones -f title="Monat 4" -f description="Physischer Einachs-Demonstrator, der sich selbst detumbled und eine Soll-Orientierung hält/verfolgt – ausschließlich mit selbstgebautem Reaction-Wheel-Aktuator, eigener Firmware (State Machine, FDIR, Regelung, FOC) und eigenem MEKF."
gh api repos/:owner/:repo/milestones -f title="Monat 5" -f description="Python-Paket \`flight-dynamics-toolkit\` – Bahnbestimmung, Manöverplanung/Delta-V-Budget, RPO-Trajektorienplanung inkl. Monte-Carlo-Validierung, gegen Orekit/GMAT cross-validiert."
gh api repos/:owner/:repo/milestones -f title="Monat 6" -f description="Vollständig integriertes, öffentlich dokumentiertes Repository \`cubesat-gnc-testbed\` mit SIL+HIL-Demonstration, technischem Bericht und direkt verwertbarem Bewerbungsportfolio."

gh issue create --title "Woche 00 – Projektaufsetzung" --body "Siehe docs/weeks/week00.md" --milestone "Monat 1"
gh issue create --title "Woche 01 – Mathematische Grundlagen & Lage-Repräsentationen" --body "Siehe docs/weeks/week01.md" --milestone "Monat 1"
gh issue create --title "Woche 02 – Lagekinematik & -dynamik" --body "Siehe docs/weeks/week02.md" --milestone "Monat 1"
gh issue create --title "Woche 03 – Bahnmechanik I (Keplerbahnen)" --body "Siehe docs/weeks/week03.md" --milestone "Monat 1"
gh issue create --title "Woche 04 – Bahnmechanik II (Störungen, J2)" --body "Siehe docs/weeks/week04.md" --milestone "Monat 1"
gh issue create --title "Woche 05 – Systemarchitektur & Sensor-/Aktuatorauswahl" --body "Siehe docs/weeks/week05.md" --milestone "Monat 2"
gh issue create --title "Woche 06 – Hardware-Bring-up" --body "Siehe docs/weeks/week06.md" --milestone "Monat 2"
gh issue create --title "Woche 07 – I/O, Timer, Interrupts" --body "Siehe docs/weeks/week07.md" --milestone "Monat 2"
gh issue create --title "Woche 08 – Zustandsmaschinen & Watchdog" --body "Siehe docs/weeks/week08.md" --milestone "Monat 2"
gh issue create --title "Woche 09 – Statische Lagebestimmung" --body "Siehe docs/weeks/week09.md" --milestone "Monat 3"
gh issue create --title "Woche 10 – Kalman-Filter-Grundlagen" --body "Siehe docs/weeks/week10.md" --milestone "Monat 3"
gh issue create --title "Woche 11 – Multiplicative EKF für Lageschätzung" --body "Siehe docs/weeks/week11.md" --milestone "Monat 3"
gh issue create --title "Woche 12 – MEKF auf Hardware" --body "Siehe docs/weeks/week12.md" --milestone "Monat 3"
gh issue create --title "Woche 13 – Quaternion-Feedback-Regelung" --body "Siehe docs/weeks/week13.md" --milestone "Monat 4"
gh issue create --title "Woche 14 – Detumbling, Momentum Dumping, Motor-PID" --body "Siehe docs/weeks/week14.md" --milestone "Monat 4"
gh issue create --title "Woche 15 – Feldorientierte Regelung (FOC)" --body "Siehe docs/weeks/week15.md" --milestone "Monat 4"
gh issue create --title "Woche 16 – Geschlossener Regelkreis auf Hardware" --body "Siehe docs/weeks/week16.md" --milestone "Monat 4"
gh issue create --title "Woche 17 – Testkampagne & Charakterisierung (Puffer)" --body "Siehe docs/weeks/week17.md" --milestone "Monat 4"
gh issue create --title "Woche 18 – Bahnbestimmung" --body "Siehe docs/weeks/week18.md" --milestone "Monat 5"
gh issue create --title "Woche 19 – Manöverplanung & Delta-V-Budget" --body "Siehe docs/weeks/week19.md" --milestone "Monat 5"
gh issue create --title "Woche 20 – Rendezvous & Proximity Operations" --body "Siehe docs/weeks/week20.md" --milestone "Monat 5"
gh issue create --title "Woche 21 – Monte-Carlo-Validierung" --body "Siehe docs/weeks/week21.md" --milestone "Monat 5"
gh issue create --title "Woche 22 – Autonome Bahnregelung (Puffer)" --body "Siehe docs/weeks/week22.md" --milestone "Monat 5"
gh issue create --title "Woche 23 – Software-in-the-Loop (SIL)" --body "Siehe docs/weeks/week23.md" --milestone "Monat 6"
gh issue create --title "Woche 24 – Hardware-in-the-Loop (HIL)" --body "Siehe docs/weeks/week24.md" --milestone "Monat 6"
gh issue create --title "Woche 25 – ECSS-orientierte Dokumentation" --body "Siehe docs/weeks/week25.md" --milestone "Monat 6"
gh issue create --title "Woche 26 – Portfolio & Bewerbung (Gesamtmeilenstein)" --body "Siehe docs/weeks/week26.md" --milestone "Monat 6"
